# NetlifyCMS Configuration
# Ex: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml
# Reference: https://www.netlifycms.org/docs/configuration-options/

# Specifies how to access the content for your site, including authentication.
backend:
  name: git-gateway
  branch: master

# "Editorial Workflow" mode for more control over the content publishing phases.
# All unpublished entries will be arranged in a board according to their status,
# and they can be further reviewed and edited before going live.
# The workflow translates editor UI actions into common Git commands
publish_mode: editorial_workflow

# Folder where uploaded files should be saved, relative to the base of the repo
media_folder: "src/assets/static/"

# Folder where uploaded files will be accessed, relative to the build site base
public_folder: "/src/content/"

# URL of published site
site_url: https://dbktv.netlify.com

# Custom logo url
logo_url: https://firebasestorage.googleapis.com/v0/b/diamondbackcloud.appspot.com/o/assets%2Fimages%2Flogos%2Ftv%2Fsvg%2Fdbktv-logo-full.svg?alt=media

# Show preview links
show_preview_links: true

# Change how filenames for entries are created and sanitized
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Collections - Determines how content types and editor fields in the UI
# generate files and content in your repository
collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI
    label_singular: "Top News Slide" # Used in the UI, ie: "New Post"
    description: >
      Use this template to create a "Top News" deck slide. The template renders a feature article with a cover image and article preview.
    folder: public/content/slides/news
    slug: "news-{{slug}}"
    preview_path: "content/news/{{slug}}.json"
    create: true # Allow users to create new documents in this collection
    extension: json # File extension to match to existing entries
    fields: # The fields each document in this collection have
      - name: "duration"
        label: "Slide duration"
        hint: "Time in milliseconds"
        widget: "number"
        default: 15000
        valueType: "int"
        min: 5000
      - name: "title"
        label: "Headline"
        widget: "string"
      - name: "href"
        label: "Article URL"
        widget: "string"
      - name: "author"
        label: "Author"
        hint: "Amazing person (or persons!!) who wrote this article! :)"
        widget: "string"
        default: "The Diamondback"
      - name: "image"
        label: "Background Image"
        widget: "object"
        fields:
          - name: "src"
            label: "Media URL"
            widget: "string"
          - name: "alt"
            label: "Alternate Text"
            widget: "string"
      - name: "body"
        label: "Article blurb"
        widget: "markdown"
  - name: "multimedia"
    label: "Multimedia"
    label_singular: "Multimedia Slide"
    description: >
      Use this template to create a "Multimedia" deck slide. The template
      renders an image or video.
    folder: public/content/slides/multimedia
    slug: "multimedia-{{slug}}"
    preview_path: "content/multimedia/{{slug}}.json"
    create: true
    extension: json
    fields:
      - name: "duration"
        label: "Slide duration"
        hint: "Time in milliseconds"
        widget: "number"
        default: 15000
        valueType: "int"
        min: 5000
      - name: "title"
        label: "Media caption"
        widget: "string"
      - name: "category"
        label: "Category"
        widget: "string"
      - name: "credit"
        label: "Credit"
        hint: "Who took this?"
        widget: "string"
        default: "The Diamondback"
      - name: "media"
        label: "Media"
        widget: "object"
        fields:
          - name: "src"
            label: "Media URL"
            widget: "string"
          - name: "video"
            label: "Is this a video?"
            widget: "boolean"
      - name: "related"
        label: "Related Article"
        widget: "object"
        required: false
        fields:
          - name: "text"
            label: "Article Headline"
            widget: "string"
          - name: "href"
            label: "Article URL"
            widget: "string"
  - name: "group"
    label: "Articles & Ads Slide"
    label_singular: "Multimedia Slide"
    description: >
      Use this template to create a "Group Articles" deck slide. The template
      renders two articles and a 300x600 advertisement.
    folder: public/content/slides/group
    slug: "group-{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "content/group/{{slug}}.json"
    create: true
    extension: json
    fields:
      - name: "duration"
        label: "Slide duration"
        hint: "Time in milliseconds"
        widget: "number"
        default: 15000
        valueType: "int"
        min: 5000
      - name: "title"
        label: "Slide title"
        hint: "This won't be displayed -- it's only here to act as a slide id"
      - name: "article1"
        label: "First article"
        widget: "object"
        fields:
          - name: "headline"
            label: "Headline"
            widget: "object"
            fields:
              - name: "text"
                label: "Article Title"
                widget: "string"
              - name: "href"
                label: "Article URL"
                widget: "string"
          - name: "author"
            label: "Author"
            hint: "Amazing person (or persons!!) who wrote this article! :)"
            widget: "string"
            default: "The Diamondback"
          - name: "category"
            label: "Category"
            widget: "string"
          - name: "blurb"
            label: "Article blurb"
            hint: "1 to 2 sentences!"
            widget: "markdown"
      - name: "article2"
        label: "Second article"
        widget: "object"
        fields:
          - name: "headline"
            label: "Headline"
            widget: "object"
            fields:
              - name: "text"
                label: "Article Title"
                widget: "string"
              - name: "href"
                label: "Article URL"
                widget: "string"
          - name: "author"
            label: "Author"
            hint: "Amazing person (or persons!!) who wrote this article! :)"
            widget: "string"
            default: "The Diamondback"
          - name: "category"
            label: "Category"
            widget: "string"
          - name: "blurb"
            label: "Article blurb"
            hint: "1 to 2 sentences!"
            widget: "markdown"
